name: Build

on:
  workflow_call:


jobs:
  modifiedrocks:
    runs-on: ubuntu-latest
    outputs:
      rocks: ${{ steps.changed-rocks.outputs.rocks }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get changed rockcraft files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            rocks/*/rockcraft.yaml
      - name: set output
        id: changed-rocks
        run: |
          components=()
          # trim file name to component name
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              component=$(echo $file | sed 's/rocks\/\(\S.*\)\/rockcraft.yaml/\1/')
              [[ ! -z "$component" ]] && components+=($component)
          done
          modified_rocks=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${components[@]}")
          echo "Modified rocks: $modified_rocks"
          echo "rocks=$modified_rocks" >> $GITHUB_OUTPUT
  build:
    needs: modifiedrocks
    if: ${{ needs.modifiedrocks.outputs.rocks != '[]' }}
    strategy:
      matrix:
        rock: ${{ fromJson(needs.modifiedrocks.outputs.rocks) }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          path: rocks/${{ matrix.rock }}
      - uses: actions/upload-artifact@v3
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
